name: App

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  goreleaser:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          repository: boythejan/ddns-go
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          ssh-strict: true
          persist-credentials: true
          clean: true
          lfs: false
          submodules: false
          set-safe-directory: true

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
          check-latest: false
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          cache: false

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v3
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist
          workdir: .
          install-only: false
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
